### ISSUE TITLE
I sugest naming the composer package same as the repository name

### ISSUE THREAD

**Issue by paveljanda** [contributte/psr7-http-message#3]
It is cleaner and people won't get confused when searching for particular repo. :)

**Comment by f3l1x** [comment]
Do you mean `contributte/psr7-http-message`?

**Comment by paveljanda** [comment]
Either that or moving `github.com/contributte/psr7-http-message` to `github.com/contributte/psr7`.

**Comment by f3l1x** [comment]
You're right, but I was thinking that name of the this repo is better reflected with full name of this PSR (seo / search / newbies), rather then in composer where you probably know what you're doing.

@matyx What do you think?

**Comment by paveljanda** [comment]
I'm used to search for/know composer packages by name and then looking for the documentation directly by typing `github.com/<composer-package-name>` into the address bar..

Look, you will have for about 150 repos in `contributte` namespace in following year. :D Maybe there will be some of them holding the name PSR-7 (PSR-7 is so cool these days..). How should one know, which one is associated with target composer package?

I understand the SEO reason. You can make the composer name `contributte/psr7-http-message` then. :P

**Comment by f3l1x** [comment]
I'll rename it to `psr7-http-message`, agreed. :taco: :+1:

**Comment by f3l1x** [comment]
Lol, 150 repos :-D

**Comment by matyx** [comment]
I agree with @paveljanda. I often go directly to github as Pavel does

**Comment by adaamz** [comment]
close?

**Comment by f3l1x** [comment]
Closed @CZechBoY

**Comment by mabar** [comment]
@paveljanda Only 130 repos in Contributte, Apitte, Nettrine, Dockette and Ninjify together 😥
