### ISSUE TITLE
Implement FileStream

### ISSUE THREAD

**Issue by f3l1x** [contributte/psr7-http-message#7]
Ideas:
-  http://discourse.slimframework.com/t/slim-3-download-files/224/2
- https://github.com/phly/psr7examples

**Comment by mabar** [comment]
For files from local filesystem there is already LazyOpenStream in Guzzle
https://github.com/guzzle/psr7/blob/master/src/LazyOpenStream.php

For files from external filesystem could be used PumpStream - callback returns content of file.
